### ISSUE TITLE
Can't unlock research

### ISSUE THREAD

**Issue by Akuukis** [Equinox-/ResearchCore#1]
Today I started a new modded world with `aux_research.xml` copied from your reference example. Medical Room didn't show up in G-menu as expected, so far so good.

Then I switch to creative, paste into some blueprint that has Medical Room in it, and switch back to survival mode. After grinding down Medical Room I realized that my inventory can't hold 10 Medical components. Exit world, edit `aux_research.xml` from 10 down to 2 components, and start world again. After grinding and welding back Medical station components are not consumed, and Medical Room doesn't show up in G-menu. Can't see anything in logs either, only that research has initiated and recognized my player. Exited world again, tried editing and commenting out various requirements for Medical Room in `aux_research.xml` but no success.

I really like the idea and would like to help this to work (as well easy to configure and debug). But how to proceed?

**Comment by Equinox-** [comment]
You have to manually start the research (think of them more like quests) before you can unlock anything.  There's also an undocumented setting on the research definition called Autostart, which will let players start the quest as soon as they have done all the dependencies.

**Comment by Akuukis** [comment]
Gotcha. Can you please give me example what to do in both cases?

**Comment by Equinox-** [comment]
Edited the [reference.xml](https://github.com/Equinox-/ResearchCore/blob/master/examples/reference.xml#L42) file to include the AutoStart attribute.

Commands aren't really documented.  Try typing `!research help` into the chat.

**Comment by Akuukis** [comment]
Now it works, thanks! Please see other new issues that I stumbled upon
