### ISSUE TITLE
Locked blueprints aren't hidden within assembler menu

### ISSUE THREAD

**Issue by Akuukis** [Equinox-/ResearchCore#11]
aux_research.xml
```
            ...
            <Unlock Type="BlueprintDefinition" Subtype="UltimateAutomaticRifle" />
            <Unlock Type="BlueprintDefinition" Subtype="Welder4" />
            <Unlock Type="BlueprintDefinition" Subtype="AngleGrinder4" />
            <Unlock Type="BlueprintDefinition" Subtype="HandDrill4" />
            ...
```

Locking BlueprintDefinition effectively "auto-removes" them from assembler and thus can't be created, so far so good. But they show up in assembler menu nevertheless. How to hide them also from within assembler menu?

I tried also this in aux_research.xml
```
            <Unlock Type="PhysicalGunObject" Subtype="UltimateAutomaticRifleItem" />
            <Unlock Type="PhysicalGunObject" Subtype="Welder4Item" />
            <Unlock Type="PhysicalGunObject" Subtype="AngleGrinder4Item" />
            <Unlock Type="PhysicalGunObject" Subtype="HandDrill4Item" />
```

but PhysicalGunObject assembler is not affected, nor it produces any warnings. Does these lines have any effect?

**Comment by Equinox-** [comment]
I'm fairly sure you can't actually remove it from the menu.  I don't remember the details.
