### ISSUE TITLE
Unlock large/small block seperately

### ISSUE THREAD

**Issue by Akuukis** [Equinox-/ResearchCore#2]
Currently if I unlock large or small block version but not other one, none of them are available to. Once I unlock both of them, only then both of them are available. Most likely that's the same cause as in another research mod [here](https://steamcommunity.com/sharedfiles/filedetails/?id=1206320070).

Please make it work so that large and small blocks could be unlocked separately.

**Comment by Equinox-** [comment]
It isn't possible because of how the cube placer works.  You could probably get them in with blueprints.
